#!/bin/bash

option=$1
cheat_name=$2
cheat_root=~/.cheat
FILE=$cheat_root/$cheat_name

# Create new cheat ie. file
if [ "$option" == "-c" ] || [ "$option" == "create" ]
then
    if [ ! -f $FILE ] 
    then
        touch $FILE
        echo -e "\e[1;32mcreated\e[0m $cheat_name"
        echo -e "================================" >> "$FILE"
        echo -e "$cheat_name                     " >> "$FILE"
        echo -e "================================" >> "$FILE"
    else
        echo -e "\e[1;31merror : '$cheat_name' already exists\e[0m" 
    fi
# Add new command in cheat
elif [ "$option" == "-a" ] || [ "$option" == "add" ]
then
    read -p "command:" command
    read -p "comment:" comment
    echo "#$comment" >> "$FILE"
    echo "$command" >> "$FILE"
    echo "----------" >> "$FILE"
    echo -e "\e[1;32madded\e[0m"
# Show cheat
elif [ "$option" == "-s" ] || [ "$option" == "show" ]
then
    cat $FILE 
# Show all cheats
elif [ "$option" == "-sa" ] || [ "$option" == "showall" ]
then
    cat $cheat_root/*
# Edit the file
elif [ "$option" == "-e" ] || [ "$option" == "edit" ] 
then
    vim $FILE
# Help
elif [ "$option" == "-h" ] || [ -z "$*" ]
then 
    echo "Syntax"
    echo "       cheat command <cheat name>"
    echo "command"
    echo "       -c     create     create new cheat-sheet"
    echo "       -a     add        add command and comment to the cheat-sheet"
    echo "       -s     show       show cheat-sheet"
    echo "       -sa    showall    show all cheat-sheet"
    echo "       -e     edit       edit cheat-sheet [vim]"
    echo "       -h     --         help"
    echo "       -d     --         delete a cheat-sheet [disabled by default]"
    echo "Storage location"
    echo "       ~/.cheat"
# Remove cheat
elif [ "$option" == "-d" ]
then
    echo "option disabled for safety"
    echo "remove manually"
    #rm $FILE
    #echo "$cheat_name deleted" 
fi

